#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2025 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT
source /assets/functions/00-container
prepare_service
PROCESS_NAME="airsonic-advanced"

airsonic_bootstrap_filesystem
airsonic_configure_database

liftoff
